data_analyzer.py

Erroneously did not check absolute value of right voltage.

fix negative right voltage trimming bug

---

README.md
data_analyzer.py

Add rsquare reporting, useful diagnostic plots, better plot formatting

---

robot-java-talonsrx/src/main/java/dc/Robot.java
robot-python-talonsrx/robot.py

Fixes the velocity units in the Talon SRX example.

Talonunits

---

README.md

ScreenSteps is not supported for 2020

Use frc-docs

---

azure-pipelines.yml
setup.py

trigger builds only on pushes to master

trigger on master

---

frc_characterization/arm_characterization/data_analyzer.py
frc_characterization/drive_characterization/data_analyzer.py
frc_characterization/elevator_characterization/data_analyzer.py

Add in axes3D imports that were removed in module nesting.

Add axes3D imports

---

frc_characterization/arm_characterization/templates/Simple/Robot.java.mako
frc_characterization/drive_characterization/templates/Simple/Robot.java.mako
frc_characterization/elevator_characterization/templates/Simple/Robot.java.mako

wpilib encoder class `setDistancePerPulse` method is based on cycles, not edges

fix ppr for wpilib encoder class

---

frc_characterization/robot/project/vendordeps/REVRobotics.json

The beta version doesn't exist anymore.

Use the kickoff instead of the beta version of the REV vendordep

---

frc_characterization/drive_characterization/templates/SparkMAX/Robot.java.mako

rightEncoderRate used leftEncoder

Fixed encoder line in Spark MAX drive template

---

frc_characterization/arm_characterization/__init__.py
frc_characterization/arm_characterization/data_analyzer.py
frc_characterization/arm_characterization/templates/Simple/Robot.java.mako
frc_characterization/arm_characterization/templates/Simple/robotconfig.py
frc_characterization/arm_characterization/templates/SparkMax/Robot.java.mako
frc_characterization/arm_characterization/templates/SparkMax/robotconfig.py
frc_characterization/arm_characterization/templates/Talon/Robot.java.mako
frc_characterization/arm_characterization/templates/Talon/robotconfig.py
frc_characterization/drive_characterization/__init__.py
frc_characterization/drive_characterization/data_analyzer.py
frc_characterization/drive_characterization/templates/Simple/Robot.java.mako
frc_characterization/drive_characterization/templates/Simple/robotconfig.py
frc_characterization/drive_characterization/templates/SparkMAX/Robot.java.mako
frc_characterization/drive_characterization/templates/SparkMAX/robotconfig.py
frc_characterization/drive_characterization/templates/Talon/Robot.java.mako
frc_characterization/drive_characterization/templates/Talon/robotconfig.py
frc_characterization/elevator_characterization/__init__.py
frc_characterization/elevator_characterization/data_analyzer.py
frc_characterization/elevator_characterization/templates/Simple/Robot.java.mako
frc_characterization/elevator_characterization/templates/Simple/robotconfig.py
frc_characterization/elevator_characterization/templates/SparkMax/Robot.java.mako
frc_characterization/elevator_characterization/templates/SparkMax/robotconfig.py
frc_characterization/elevator_characterization/templates/Talon/Robot.java.mako
frc_characterization/elevator_characterization/templates/Talon/robotconfig.py

"Pulses per rev" is fraught; "edges per rev" is unambiguous.

change "pulses per rev" to "edges per rev", clarify instructions

---

frc_characterization/arm_characterization/data_analyzer.py
frc_characterization/drive_characterization/data_analyzer.py
frc_characterization/elevator_characterization/data_analyzer.py

I walked a user through diagnosing this on the FRC Discord about a month ago, and then I forgot to PR the fix! Fortunately #88 reminded me. Please don't merge this until the user who opened that issue confirms that this fix works.
Closes #88.

Fix tk+matplotlib on macOS Mojave

---

frc_characterization/simplemotor_characterization/__init__.py
frc_characterization/simplemotor_characterization/data_analyzer.py
frc_characterization/simplemotor_characterization/templates/Neo/Robot.java.mako
frc_characterization/simplemotor_characterization/templates/Neo/robotconfig.py
frc_characterization/simplemotor_characterization/templates/Simple/Robot.java.mako
frc_characterization/simplemotor_characterization/templates/Simple/robotconfig.py
frc_characterization/simplemotor_characterization/templates/SparkMax/Robot.java.mako
frc_characterization/simplemotor_characterization/templates/SparkMax/robotconfig.py
frc_characterization/simplemotor_characterization/templates/Talon/Robot.java.mako
frc_characterization/simplemotor_characterization/templates/Talon/robotconfig.py

Should be useful for turrets and swerve modules

Add radians and degrees mode to simple motor characterization

---

frc_characterization/drive_characterization/data_analyzer.py
frc_characterization/simplemotor_characterization/data_analyzer.py

Calculate velocity instead of position gains by default for drive and simplemotor

---

frc_characterization/arm_characterization/data_analyzer.py
frc_characterization/cli/__init__.py
frc_characterization/drive_characterization/data_analyzer.py
frc_characterization/elevator_characterization/data_analyzer.py
frc_characterization/simplemotor_characterization/data_analyzer.py

> Because of an update to the black formatter, the CI fails any frc-char PR, forcing it to add a million formatting changes that have nothing to do with the purpose of the PR. I was thinking of a quickly-merged PR that only runs the black formatter, updating the repo to a state that the formatter accepts. then PRs can be rebased on that, eliminating the need for duplicate formatting changes in every PR.

Update black formatting

---

frc_characterization/arm_characterization/templates/SparkMax_Brushed/robotconfig.py
frc_characterization/arm_characterization/templates/SparkMax_Brushless/robotconfig.py
frc_characterization/drive_characterization/templates/SparkMax_Brushed/robotconfig.py
frc_characterization/drive_characterization/templates/SparkMax_Brushless/robotconfig.py
frc_characterization/elevator_characterization/templates/SparkMax_Brushed/robotconfig.py
frc_characterization/elevator_characterization/templates/SparkMax_Brushless/robotconfig.py
frc_characterization/simplemotor_characterization/templates/SparkMax_Brushed/robotconfig.py
frc_characterization/simplemotor_characterization/templates/SparkMax_Brushless/robotconfig.py

Fix "poject"->"project" typo

---

frc_characterization/logger_analyzer/templates/build.gradle.mako

Update generated project to 2021 beta 2

---

frc_characterization/robot/project/src/main/java/dc/SimEnabler.java

Fix import path for DriverStationSim

---

frc_characterization/newproject/__init__.py

Moved the action of the code deploy to a separate background worker
thread that updates the GUI through a process queue function every 10
ms. This helps the deploy process not freeze the application whenever
deploying.

Multithreading Code Deploy

---

frc_characterization/newproject/__init__.py

Open config file directly instead of erroneously opening its parent dir

---

frc_characterization/logger_analyzer/data_analyzer.py

Still need trackwidth characterization to verify this works.
Should close #166

Add trackwidth conversions

---

frc_characterization/logger_analyzer/data_logger.py

Supposed to close #170.
Hasn't been tested yet.

Add gyro measurement for trackwidth

---

frc_characterization/logger_analyzer/data_analyzer.py

Fixed a bug that caused the trackwidth unit conversions from rotational to translational to crash.

Fix trackwidth units bug

---

frc_characterization/logger_analyzer/templates/Robot.java.mako

Unnecessary division by 4 on the Encoder EPR

---

frc_characterization/logger_analyzer/templates/Robot.java.mako

Credit [here](https://www.chiefdelphi.com/t/falcon-fx-velocity-pid-and-stubborn-error-from-getclosedlooperror/392357/6?u=jdaming) for discovering the bug
@AustinShalit / @PeterJohnson this should probably be pushed ASAP.  I have not tested it.

Fix issue with Integer Division
