robot-java-talonsrx/src/dc/Robot.java
In the Java SRX code, the rate was being read using getSelectedSensorPosition instead of getSelectedSensorVelocity. This is not an issue in the Python code.
=> Fix usage of wrong function to get velocity

data_analyzer.py
Added interactive 3d plots of voltage over the entire velocity-acceleration plane, including both scatterplot and plane-of-best-fit as computed from the regression.  Very cool visualization that will help teams understand what the code is actually doing.
=> Add 3D plots of voltage over velocity-acceleration plane

README.md
The readme points to the wrong package, updated with the right one `frc-characterization`.  Issue #36
=> Fix incorrect pypi package name to install in readme. 

setup.py
This fixes broken auto-versioning on Azure because of the way Azure checks out the commit it intends to build. Sorry about this (I should have looked at Azure's output a little closer).
=> Fix broken auto versioning on non-master branches

arm_characterization/data_analyzer.py, drive_characterization/data_analyzer.py, elevator_characterization/data_analyzer.py
When this occurs, velocity can be treated as a model input to avoid
numerical instability. The feedback gains produced appear to be what the
original model converges to as ka approaches zero.
With the alternate model, `kp = kv * K[0, 0]` is used because the gain
produced by LQR is for velocity. We can use the feedforward equation
`u = kv * v` to convert velocity to voltage. `kd = 0` because velocity
was an input; we don't need feedback control to command it.
=> Handle edge case when ka = 0

frc_characterization/arm_characterization/templates/Neo/robotconfig.py, frc_characterization/arm_characterization/templates/Simple/robotconfig.py, frc_characterization/arm_characterization/templates/SparkMax/robotconfig.py, frc_characterization/arm_characterization/templates/Talon/robotconfig.py, frc_characterization/drive_characterization/templates/Neo/robotconfig.py, frc_characterization/drive_characterization/templates/Simple/robotconfig.py, frc_characterization/drive_characterization/templates/SparkMAX/robotconfig.py, frc_characterization/drive_characterization/templates/Talon/robotconfig.py, frc_characterization/elevator_characterization/templates/Neo/robotconfig.py, frc_characterization/elevator_characterization/templates/Simple/robotconfig.py, frc_characterization/elevator_characterization/templates/SparkMax/robotconfig.py, frc_characterization/elevator_characterization/templates/Talon/robotconfig.py
allows config files to tolerate omission of trailing commas in lists
=> replace parens with square brackets in config files

frc_characterization/drive_characterization/templates/Neo/Robot.java.mako, frc_characterization/drive_characterization/templates/Neo/robotconfig.py, frc_characterization/drive_characterization/templates/Simple/Robot.java.mako, frc_characterization/drive_characterization/templates/Simple/robotconfig.py, frc_characterization/drive_characterization/templates/SparkMAX/Robot.java.mako, frc_characterization/drive_characterization/templates/SparkMAX/robotconfig.py, frc_characterization/drive_characterization/templates/Talon/Robot.java.mako, frc_characterization/drive_characterization/templates/Talon/robotconfig.py
Somehow I missed this one when I grepped the wpilib javadoc for "gyro" to make sure that I didn't miss any gyros to add for the track width PR.
=> Add AnalogGyro as a gyro option

frc_characterization/arm_characterization/templates/Neo/Robot.java.mako, frc_characterization/arm_characterization/templates/SparkMax/Robot.java.mako, frc_characterization/arm_characterization/templates/Talon/Robot.java.mako, frc_characterization/drive_characterization/templates/Neo/Robot.java.mako, frc_characterization/drive_characterization/templates/Neo/robotconfig.py, frc_characterization/drive_characterization/templates/Simple/robotconfig.py, frc_characterization/drive_characterization/templates/SparkMAX/Robot.java.mako, frc_characterization/drive_characterization/templates/SparkMAX/robotconfig.py, frc_characterization/drive_characterization/templates/Talon/Robot.java.mako, frc_characterization/drive_characterization/templates/Talon/robotconfig.py, frc_characterization/elevator_characterization/templates/Neo/Robot.java.mako, frc_characterization/elevator_characterization/templates/SparkMax/Robot.java.mako, frc_characterization/elevator_characterization/templates/Talon/Robot.java.mako
This fixes a couple of comments that said the non-Talon SRX templates assume a Talon SRX. It also clarifies that you need to use `WPI_TalonSRX` if you're using a Pigeon IMU connected to a Talon SRX.
Fixes #73.
=> Remove and clarify erroneous references to the Talon SRX in comments

frc_characterization/drive_characterization/templates/Talon/robotconfig.py
Some users were getting confused about how to use Talon FXes with frc-characterization. This adds a note on how that can be done.
Please don't merge before #68—you won't be able to use `WPI_TalonFX` until we have the latest CTRE vendordep.
=> Add note about using Talon FXes

frc_characterization/drive_characterization/templates/Neo/Robot.java.mako, frc_characterization/drive_characterization/templates/Simple/Robot.java.mako, frc_characterization/drive_characterization/templates/SparkMAX/Robot.java.mako, frc_characterization/drive_characterization/templates/Talon/Robot.java.mako, frc_characterization/drive_characterization/templates/Talon/robotconfig.py
It occurred to me that you can actually have your Pigeon IMU connected to a Talon when you're using a Neo/PWM drivetrain. The `WPI_Talon*` import was missing from the non-Talon projects, which would be a problem if anyone has the setup I just described. This fixes that.
=> Fix missing import for Pigeon on a Talon with a non-Talon project

frc_characterization/drive_characterization/templates/Simple/Robot.java.mako
This bug would probably never be encountered in the wild because no sane
person would ever have an asymmetrical number of motors on their
drivetrain... But it's a bug nevertheless.
=> Fix drive Simple template generating the wrong number of motor instantiations

frc_characterization/drive_characterization/templates/Neo/Robot.java.mako, frc_characterization/drive_characterization/templates/Neo/robotconfig.py, frc_characterization/drive_characterization/templates/Simple/Robot.java.mako, frc_characterization/drive_characterization/templates/Simple/robotconfig.py, frc_characterization/drive_characterization/templates/SparkMax/Robot.java.mako, frc_characterization/drive_characterization/templates/SparkMax/robotconfig.py, frc_characterization/drive_characterization/templates/Talon/Robot.java.mako, frc_characterization/drive_characterization/templates/Talon/robotconfig.py
Closes #86. Sorry about this. I had missed that you could pass a `SerialPort` to the NavX constructor when I made the track width PR.
=> Add imports and notes about using the NavX SerialPort.Port.kMXP

frc_characterization/drive_characterization/templates/Neo/robotconfig.py, frc_characterization/drive_characterization/templates/SparkMax/robotconfig.py, frc_characterization/drive_characterization/templates/Talon/robotconfig.py
A user on the FRC Discord had an issue with this, so it seemed worthwhile to add a note about how you're supposed to order your motor controller ports.
=> Clarify motor port ordering for the Talon SRX and Spark MAX robotconfigs

frc_characterization/simplemotor_characterization/data_analyzer.py
It was set to 5s and should be 20ms like the others.
=> Fix SimpleMotor default feedback controller sample period

frc_characterization/arm_characterization/templates/Talon/Robot.java.mako, frc_characterization/arm_characterization/templates/Talon/robotconfig.py, frc_characterization/elevator_characterization/templates/Talon/Robot.java.mako, frc_characterization/elevator_characterization/templates/Talon/robotconfig.py, frc_characterization/simplemotor_characterization/templates/Talon/Robot.java.mako
There were some missing TalonFX imports and wrong encoder configuration in non-drivetrain templates.
=> Integrate/document TalonFX into non-drivetrain templates

frc_characterization/cli/__init__.py
The command-line interface menu now allows for going back to the main menu without requiring to exit.
Also fixes #44
=> Cleanup command-line interface menu

frc_characterization/arm_characterization/data_analyzer.py, frc_characterization/drive_characterization/data_analyzer.py, frc_characterization/elevator_characterization/data_analyzer.py, frc_characterization/simplemotor_characterization/data_analyzer.py
This adds an extra measurement delay input box in the data analyzer, along with appropriate defaults for the various motor controller presets. Note that this changes the behavior of the loop type dropdown so that it now applies the presets over whatever the user has when the dropdown is changed; this is to make it so that the measurement delay preset is changed when the user changes the loop type automatically.
Closes #124.
=> Add LQR latency compensation

setup.py
See https://stackoverflow.com/a/64661876. Numpy 1.19.3 used  a different
version of OpenBLAS to work around a Windows bug
(https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html).
This change broke Linux, so it was reverted in 1.19.4. Therefore, we
install 1.19.3 for Windows and the latest version for all other
platforms.
Note that this Windows bug only affects 64-bit versions of Python.
=> Lock Windows numpy version to 1.19.3

frc_characterization/logger_analyzer/data_analyzer.py, frc_characterization/logger_analyzer/templates/Robot.java.mako
- Fixes the `gyroSupplier` getting left as null if no gyro is selected.
- Fixes crashes when "All Combined", "Left Combined", or "Right Combined" are selected.
- Fixes some small naming inconsistencies.
=> Fix small bugs introduced in refactor

frc_characterization/logger_analyzer/templates/Robot.java.mako
It isn't used, so it just takes up bandwidth and can cause loop
overruns, which is bad for consistent data collection at 200Hz.
=> Disable LiveWindow telemetry during data collection

frc_characterization/logger_analyzer/__init__.py, frc_characterization/newproject/__init__.py
... by replacing it with a method that takes a directory not a filepath.
* Reimplements importlib.resources.files() locally because it does not exist in
versions prior to Python 3.9.
* Should properly fix #158 in all the locations it occurs.
* This reverts commit 76cd65b777eb2d3eb151d923dee7c297fb552514
=> Fixes IsADirectoryError from importlib.resources.path()

frc_characterization/newproject/__init__.py
This allows error messages to point to the config source itself.
Alternative to #175 and #182.
=> Replace ast.literal_eval with compile then eval

frc_characterization/logger_analyzer/templates/Robot.java.mako, frc_characterization/logger_analyzer/templates/configs/pwfconfig.py, frc_characterization/newproject/__init__.py, frc_characterization/robot/project/vendordeps/playingwithfusion2021.json
- Added PWF Config option to the UI.
- Added Venom specific config.py.   (Basically the same as simple, but with Venom specific comments)
- Robot.Java.Mako to support CANVenom class and to use built-in Venom encoder
=> Added support for PWF Venom motor to Robot Characterization
